name: Build Secret Scanner

on:
  push:
    paths:
      - 'patterns.json'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    name: Build on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile --name secret-scanner main.py

      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: dist/secret-scanner*

  package-deb:
    runs-on: ubuntu-latest
    needs: build
    name: Create .deb package
    steps:
      - uses: actions/checkout@v3

      - name: Install fpm
        run: sudo apt-get install -y ruby ruby-dev build-essential && sudo gem install --no-document fpm

      - name: Download built executable
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-latest-build
          path: dist/

      - name: Create .deb package
        run: |
          mkdir -p pkg/usr/local/bin
          cp dist/secret-scanner pkg/usr/local/bin/secret-scanner
          fpm -s dir -t deb -n secret-scanner -v 1.0 pkg/
          
      - name: Upload .deb package
        uses: actions/upload-artifact@v3
        with:
          name: deb-package
          path: "*.deb"
